### ISSUE TITLE
bad case on filenames in the solution .sln

### ISSUE THREAD

**Issue by franck-gaspoz** [OrbitalShell/Orbital-Shell#19]
bad case on filenames in the solution .sln

**Comment by franck-gaspoz** [comment]
forget ?

**Comment by Yobatman38** [comment]
Done. The problem was already solved in last version.

**Comment by franck-gaspoz** [comment]
YAHOUU ! thanks a lot @Yobatman38 
so, did you check if you can close the ticket at:
https://github.com/orgs/OrbitalShell/projects/1#card-55149732
this would be the first ticket closed on the project (in this version). so you collect all the first times, with 'first pull request'.
what will be your next first ? 🤸‍♀️

**Comment by franck-gaspoz** [comment]
i got the response now 🙄

**Comment by franck-gaspoz** [comment]
the ticket moves in real timesin my navigator when you make it change column. nice software

**Comment by Yobatman38** [comment]
Oh yeaah !

**Comment by franck-gaspoz** [comment]
if you like smiley like me, just type : and try to input the name of one of this extended unicode symbol 💩
