### ISSUE TITLE
add other ci/cd cool target: DOCKER

### ISSUE THREAD

**Issue by franck-gaspoz** [OrbitalShell/Orbital-Shell#29]
add other ci/cd cool target DOCKER

**Comment by Yobatman38** [comment]
Hello,
An Ubuntu Docker image is now published on Docker Hub after each commit on "master" branch.
All related bugs have been corrected.
Julien

**Comment by franck-gaspoz** [comment]
Cool 😊 merci pour l’info.  Bonne idée de passer par le mail de l’orga (faut vraiment que je regarde mes mails) Provenance : Courrier pour Windows 10 De : YoBatmanEnvoyé le :lundi 22 février 2021 10:01À : OrbitalShell/Orbital-ShellCc : Franck Gaspoz; AuthorObjet :Re: [OrbitalShell/Orbital-Shell] add other ci/cd cool target: DOCKER (#29) Hello,An Ubuntu Docker image is now published on Docker Hub after each commit on "master" branch.All related bugs have been corrected.Julien—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
